version: "3"
services:
  mariaDB:
    image: mariadb:latest
    container_name: TodoDatabase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: TodoDatabase
    ports:
      - '3306:3306'
    volumes:
      - ./todo.sql:/docker-entrypoint-initdb.d/sql-db.sql
